"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// panels templates: slider (bar and controls), hitogram and settings
exports.SLIDER_TEMPLATE = "\n<div rv-focus-member class=\"rv-rangeslider\">\n    <div class=\"slider-content\">\n        <div class=\"slider-bar\">\n            <div id=\"nouislider\" class=\"slider-widget\"></div>\n            <div class=\"slider-controls\"></div>\n        </div>\n    </div>\n</div>";
// slider bar controls (lock, loop, previous, next, play/pause, refresh, delay, export gif)
exports.LOCK_BAR_TEMPLATE = "\n<div class=\"slider-bar-control slider-lock-control\">\n    <md-button\n        ng-controller=\"LockSliderCtrl as ctrl\"\n        aria-label=\"{{ !ctrl.isLocked ? 'plugins.rangeSlider.bar.lock' : 'plugins.rangeSlider.bar.unlock' | translate }}\"\n        class=\"md-icon-button primary\"\n        ng-click=\"ctrl.lock()\">\n        <md-tooltip>{{ !ctrl.value.isLocked ? 'plugins.rangeSlider.bar.lock' : 'plugins.rangeSlider.bar.unlock' | translate }}</md-tooltip>\n        <md-icon ng-if=\"ctrl.value.isLocked\">" + createSVG('lock') + "</md-icon>\n        <md-icon ng-if=\"!ctrl.value.isLocked\">" + createSVG('lockOpen') + "</md-icon>\n    </md-button>\n</div>";
exports.LOOP_BAR_TEMPLATE = "\n<div class=\"slider-bar-control slider-loop-control\">\n    <md-button\n        ng-controller=\"LoopSliderCtrl as ctrl\"\n        aria-label=\"{{ !ctrl.isLooped ? 'plugins.rangeSlider.bar.loop' : 'plugins.rangeSlider.bar.unloop' | translate }}\"\n        class=\"md-icon-button primary\"\n        ng-click=\"ctrl.loop()\">\n        <md-tooltip>{{ !ctrl.value.isLooped ? 'plugins.rangeSlider.bar.loop' : 'plugins.rangeSlider.bar.unloop' | translate }}</md-tooltip>\n        <md-icon>" + createSVG('loop') + "</md-icon>\n    </md-button>\n</div>";
exports.PLAY_BAR_TEMPLATE = "\n<div class=\"slider-bar-control slider-play-control\">\n    <md-button\n        ng-controller=\"StepSliderCtrl as ctrl\"\n        aria-label=\"{{ 'plugins.rangeSlider.bar.previous' | translate }}\"\n        class=\"md-icon-button primary\"\n        ng-click=\"ctrl.step('down')\">\n        <md-tooltip>{{ 'plugins.rangeSlider.bar.previous' | translate }}</md-tooltip>\n        <md-icon>" + createSVG('previous') + "</md-icon>\n    </md-button>\n    <md-button\n        ng-controller=\"PlaySliderCtrl as ctrl\"\n        aria-label=\"{{ ctrl.value.isPlaying ? 'plugins.rangeSlider.bar.pause' : 'plugins.rangeSlider.bar.play' | translate }}\"\n        class=\"md-icon-button primary\"\n        ng-click=\"ctrl.play()\">\n        <md-tooltip>{{ ctrl.value.isPlaying ? 'plugins.rangeSlider.bar.pause' : 'plugins.rangeSlider.bar.play' | translate }}</md-tooltip>\n        <md-icon ng-if=\"ctrl.value.isPlaying\">" + createSVG('pause') + "</md-icon>\n        <md-icon ng-if=\"!ctrl.value.isPlaying\">" + createSVG('play') + "</md-icon>\n    </md-button>\n    <md-button\n        ng-controller=\"StepSliderCtrl as ctrl\"\n        aria-label=\"{{ 'plugins.rangeSlider.bar.foward' | translate }}\"\n        class=\"md-icon-button primary\"\n        ng-click=\"ctrl.step('up')\">\n        <md-tooltip>{{ 'plugins.rangeSlider.bar.foward' | translate }}</md-tooltip>\n        <md-icon>" + createSVG('next') + "</md-icon>\n    </md-button>\n</div>";
exports.REFRESH_BAR_TEMPLATE = "\n<div class=\"slider-bar-control slider-refresh-control\">\n    <md-button\n        ng-controller=\"RefreshSliderCtrl as ctrl\"\n        aria-label=\"{{ 'plugins.rangeSlider.bar.refresh' | translate }}\"\n        class=\"md-icon-button primary rv-slider-refresh\"\n        ng-click=\"ctrl.refresh()\">\n        <md-tooltip>{{ 'plugins.rangeSlider.bar.refresh' | translate }}</md-tooltip>\n        <md-icon>" + createSVG('refresh') + "</md-icon>\n    </md-button>\n</div>";
exports.DELAY_BAR_TEMPLATE = "\n<div ng-controller=\"DelaySliderCtrl as ctrl\" class=\"slider-bar-control slider-delay-control\">\n    <md-input-container class=\"md-block\" md-no-float flex>\n        <label>{{ 'plugins.rangeSlider.bar.delay' | translate }}</label>\n        <md-select\n            aria-label=\"{{ 'plugins.rangeSlider.bar.delay' | translate }}\"\n            ng-model=\"ctrl.selectedDelay\"\n            ng-change=\"ctrl.selectDelay()\">\n            <md-option ng-repeat=\"(key, value) in { 3000: '3 sec', 4000: '4 sec', 5000: '5 sec', 6000: '6 sec', 7000: '7 sec' }\" ng-value=\"{{ key }}\">\n                {{ value }}\n            </md-option>\n        </md-select>\n    </md-input-container>\n</div>";
exports.EXPORT_BAR_TEMPLATE = "\n<div class=\"slider-bar-control slider-export-control\">\n    <span>\n        <md-switch\n            ng-controller=\"ExportSliderCtrl as ctrl\"\n            aria-label=\"{{ 'plugins.rangeSlider.bar.tooltip.gif' | translate }}\"\n            class=\"rv-slider-switch\"\n            ng-class=\"md-primary\"\n            ng-model=\"ctrl.export\"\n            ng-change=\"ctrl.selectExport()\">\n            <label>{{ 'plugins.rangeSlider.bar.gif' | translate }}</label>\n        </md-switch>\n        <md-tooltip>{{ 'plugins.rangeSlider.bar.tooltip.gif' | translate }}</md-tooltip>\n    </span>\n</div>";
function createSVG(icon) {
    var svg = {
        'histo': '<path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z"></path>',
        'lock': '<path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm-6 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2z"></path>',
        'lockOpen': '<path d="M12 17c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm6-9h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6h1.9c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm0 12H6V10h12v10z"></path>',
        'loop': '<path d="M12 4V1L8 5l4 4V6c3.31 0 6 2.69 6 6 0 1.01-.25 1.97-.7 2.8l1.46 1.46C19.54 15.03 20 13.57 20 12c0-4.42-3.58-8-8-8zm0 14c-3.31 0-6-2.69-6-6 0-1.01.25-1.97.7-2.8L5.24 7.74C4.46 8.97 4 10.43 4 12c0 4.42 3.58 8 8 8v3l4-4-4-4v3z"></path>',
        'next': '<path d="M6 18l8.5-6L6 6v12zM16 6v12h2V6h-2z"></path>',
        'previous': '<path d="M6 6h2v12H6zm3.5 6l8.5 6V6z"></path>',
        'play': '<path d="M8 5v14l11-7z"></path>',
        'pause': '<path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"></path>',
        'refresh': '<path d="M17.65 6.35C16.2 4.9 14.21 4 12 4c-4.42 0-7.99 3.58-7.99 8s3.57 8 7.99 8c3.73 0 6.84-2.55 7.73-6h-2.08c-.82 2.33-3.04 4-5.65 4-3.31 0-6-2.69-6-6s2.69-6 6-6c1.66 0 3.14.69 4.22 1.78L13 11h7V4l-2.35 2.35z"></path>'
    };
    return "<svg xmlns=\"http://www.w3.org/2000/svg\" fit=\"\" height=\"100%\" width=\"100%\" preserveAspectRatio=\"xMidYMid meet\" viewBox=\"0 0 24 24\" focusable=\"false\">\n            <g id=\"slider" + icon + "\">" + svg[icon] + "</g></svg>";
}
