"use strict";
/*
loginmenu = The form for the login
startmenu =
form = Teh from fro extraction
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.loginmenu = "\n<div ng-controller=\"connexionCtrl as ctrl\">\n    <div><h2>{{ 'plugins.geosys.login' | translate }}</h2></div>\n    <div>{{ 'plugins.geosys.username' | translate }} : </div>\n    <div><input type=\"text\" id=\"username\" placeholder=\"{{ 'plugins.geosys.username' | translate }}\"/></div>\n    <div>{{ 'plugins.geosys.password ' | translate }} : </div>\n    <div><input type=\"password\" id=\"password\" placeholder=\"{{ 'plugins.geosys.password ' | translate }}\"/></div>\n\n    <div class=\"rv-subsection\">\n        <md-button class=\"md-primary md-button\"\n        ng-click=\"ctrl.submitConn()\">\n            {{ 'plugins.geosys.submit' | translate }}\n            <md-tooltip>{{ 'plugins.geosys.submit' | translate }}</md-tooltip>\n        </md-button>\n\n    </div>\n</div>\n";
exports.startmenu = "\n<div>\n    <ul>\n    </u>\n</div>";
exports.formExtraire = "<div ng-controller=\"SubmitCtrl as ctrl\">\n    \n    <div><h2>{{ 'plugins.geosys.extrac' | translate }}</h2></div>\n    <div class=\"\">\n        <div class=\"rv-subsection\">\n            <div>{{ 'plugins.geosys.envir' | translate }}</div>\n            <div>\n                <select type=\"text\" id=\"env\" placeholder=\"Select something\">\n                    {dropdownenv}\n                </select>\n            </div>\n        </div>\n        \n        <div class=\"rv-subsection\">\n            <div>{{ 'plugins.geosys.themet' | translate }}</div>\n            <select type=\"text\" id=\"theme\" placeholder=\"Select something\">\n                {dropdowntheme}\n            </select>\n        </div>\n        \n        <div class=\"rv-subsection\">\n            <div>{{ 'plugins.geosys.idUT' | translate }}</div>\n            <input type=\"text\" name=\"idlot\" id=\"idlot\" value=\"1\"/>\n        </div>\n        \n        <div class=\"rv-subsection\">\n            <div>{{ 'plugins.geosys.clip' | translate }}</div>\n            <div><input type=\"checkbox\" name=\"clip\" id=\"clip\" value=\"non\" checked=\"oui\"/></div>\n        </div>\n\n        <div class=\"rv-subsection\">\n            <div>{{ 'plugins.geosys.where' | translate }}<br></div>\n            <div><input type=\"text\" name=\"whereclause\" id=\"whereclause\" value=\"\" placeholder=\"Where ...\"/></div>\n        </div>\n        \n        <div class=\"rv-subsection\">\n            <div>{{ 'plugins.geosys.geome' | translate }}</div>\n            <div><input type=\"text\" name=\"geom\" id=\"geom\" value=\"geom\"/></div>\n        </div>\n        \n        <div class=\"rv-subsection\">\n            <md-button class=\"md-primary md-button\"\n            ng-click=\"ctrl.submitForm()\">\n                {{ 'plugins.geosys.submit' | translate }}\n                <md-tooltip>{{ 'plugins.geosys.submit' | translate }}</md-tooltip>\n            </md-button>\n\n    </div>\n    </div>        \n</div>";
exports.fromPlanifier = "\n<div ng-controller=\"submitFromP as ctrl\">\n<div>\n    <div>{{ 'plugins.geosys.envir' | translate }}</div>\n    <div></div>\n</div>\n<div>\n    <div>{{ 'plugins.geosys.themet' | translate }}</div>\n    <div></div>\n</div>\n<div>\n    <div>{{ 'plugins.geosys.zoneTrv' | translate }}</div>\n    <div></div>\n</div>\n<div>\n    <div>{{ 'plugins.geosys.idUT' | translate }}</div>\n    <div></div>\n</div>\n<div>\n    <div>{{ 'plugins.geosys.typeTrv' | translate }}</div>\n    <div></div>\n</div>\n<div>\n    <div>{{ 'plugins.geosys.classe' | translate }}</div>\n    <div></div>\n</div>\n<div>\n    <div>{{ 'plugins.geosys.datefinprv' | translate }}</div>\n    <div></div>\n</div>\n<div>\n    <div>{{ 'plugins.geosys.log' | translate }}</div>\n    <div></div>\n</div>\n<div>\n    <md-button class=\"md-primary md-button\"\n    ng-click=\"ctrl.submitFormP()\">\n        {{ 'plugins.geosys.submit' | translate }}\n        <md-tooltip>{{ 'plugins.geosys.submit' | translate }}</md-tooltip>\n    </md-button>\n</div>\n\n</div>";
