"use strict";
/*
loginmenu = The form for the login
startmenu =
form = Teh from fro extraction
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.loginmenu = "\n<div ng-controller=\"connexionCtrl as ctrl\">\n    <div><h2>{{ 'plugins.testing.login' | translate }}</h2></div>\n    <div>username : </div>\n    <div><input type=\"text\" id=\"username\" placeholder=\"username\"/></div>\n    <div>Password : </div>\n    <div><input type=\"password\" id=\"password\" placeholder=\"password\"/></div>\n\n    <div class=\"rv-subsection\">\n        <md-button class=\"md-primary md-button\"\n        ng-click=\"ctrl.submitConn()\">\n            {{ 'plugins.testing.submit' | translate }}\n            <md-tooltip>{{ 'plugins.testing.submit' | translate }}</md-tooltip>\n        </md-button>\n\n    </div>\n</div>\n";
exports.startmenu = "\n<div>\n    <ul>\n    </u>\n</div>";
exports.form = "<div ng-controller=\"SubmitCtrl as ctrl\">\n    <div><h2>{{ 'plugins.testing.extrac' | translate }}</h2></div>\n    <div class=\"rv-subsection\">\n        <div>{{ 'plugins.testing.envir' | translate }}</div>\n        <div>\n            <select type=\"text\" id=\"env\" placeholder=\"Select something\">\n                {dropdownenv}\n            </select>\n        </div>\n    </div>\n    \n    <div class=\"rv-subsection\">\n        <div>{{ 'plugins.testing.themet' | translate }}</div>\n        <select type=\"text\" id=\"theme\" placeholder=\"Select something\">\n            {dropdowntheme}\n        </select>\n    </div>\n    \n    <div class=\"rv-subsection\">\n        <div>{{ 'plugins.testing.idlot' | translate }}</div>\n        <input type=\"text\" name=\"idlot\" id=\"idlot\" value=\"1\"/>\n    </div>\n    \n    <div class=\"rv-subsection\">\n        Si Clip:<br>\n        <input type=\"text\" name=\"clip\" id=\"clip\" value=\"Oui\"/>\n    </div>\n\n    <div class=\"rv-subsection\">\n        Entrez un where clause:<br>\n        <input type=\"text\" name=\"whereclause\" id=\"whereclause\" value=\"Ajout\"/>\n    </div>\n    \n    <div class=\"rv-subsection\">\n        <div>{{ 'plugins.testing.idlot' | translate }}</div>\n        <input type=\"text\" name=\"geom\" id=\"geom\" value=\"geom\"/>\n    </div>\n    \n    <div class=\"rv-subsection\">\n        <md-button class=\"md-primary md-button\"\n        ng-click=\"ctrl.submitForm()\">\n            {{ 'plugins.testing.submit' | translate }}\n            <md-tooltip>{{ 'plugins.testing.submit' | translate }}</md-tooltip>\n        </md-button>\n\n    </div>\n            \n</div>";
